name: Android CI

on:
  push

jobs:
  apk:
    name: Build Debug APK and Upload Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: omcast-debug-${{github.run_number}}
          path: app/build/outputs/apk/debug/app-debug.apk